name: Testing

on:
  push:
    branches:
      - master

  pull_request:
    branches: "**"
    types:
      - ready_for_review
      - synchronize
      - opened

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist --no-suggest --optimize-autoloader

      - name: Install Node Modules
        run: yarn install

      - name: Build Assets
        run: yarn production

      - name: Generate key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Execute PHPUnit tests
        run: php artisan test --configuration=phpunit.xml.dist
